import { FIXTURE_RANGERS_DIRT_TEAM_ID } from "@/department-teams/fixtureDepartmentAccess";
import { LOCAL_FIELD_FIXTURE } from "@/field-reports/localFieldFixture";

import type {
  CapabilityContext,
  DepartmentOpsContext,
  DepartmentOverview,
  LogisticsDeskModel,
  OperationsCenterModel,
  PlanningTableModel,
} from "@/department-ops/types";

export const LOCAL_DEPARTMENT_OPS_CONTEXT: DepartmentOpsContext = {
  eventId: LOCAL_FIELD_FIXTURE.eventId,
  eventLabel: LOCAL_FIELD_FIXTURE.eventLabel,
  departmentId: "66666666-6666-4666-8666-666666666666",
  departmentLabel: "Rangers",
  timeZone: "America/Los_Angeles",
  selectedTeamId: null,
  selectedTeamLabel: null,
  asOf: "2027-07-04T18:00:00.000Z",
};

export const LOCAL_CAPABILITIES: CapabilityContext = {
  isDepartmentLead: true,
  hasLogistics: true,
  hasOperations: true,
  hasPlanning: true,
  hasFieldReportPermission: true,
  hasIncidentCommand: true,
  hasEquipmentVisibility: true,
};

const dayShiftId = "99999999-9999-4999-8999-999999999999";
const swingShiftId = "99999999-9999-4999-8999-999999999998";
const overnightShiftId = "99999999-9999-4999-8999-999999999997";
const dirtTeamId = "77777777-7777-4777-8777-777777777771";
const commandTeamId = "77777777-7777-4777-8777-777777777772";

const availableLogisticsEquipment = [
  {
    checkoutId: null,
    equipmentItemId: "equipment-safety-vest",
    name: "Safety Vest",
    assetTag: "VEST-04",
    status: "available" as const,
    checkedOutAt: null,
  },
  {
    checkoutId: null,
    equipmentItemId: "equipment-radio-13",
    name: "Radio 13",
    assetTag: "RDO-13",
    status: "available" as const,
    checkedOutAt: null,
  },
  {
    checkoutId: null,
    equipmentItemId: "equipment-radio-14",
    name: "Radio 14",
    assetTag: "RDO-14",
    status: "available" as const,
    checkedOutAt: null,
  },
  {
    checkoutId: null,
    equipmentItemId: "equipment-radio-15",
    name: "Radio 15",
    assetTag: "RDO-15",
    status: "available" as const,
    checkedOutAt: null,
  },
];

export const LOCAL_DEPARTMENT_OVERVIEW: DepartmentOverview = {
  context: LOCAL_DEPARTMENT_OPS_CONTEXT,
  selectedShiftId: dayShiftId,
  shifts: [
    {
      shiftId: dayShiftId,
      title: "Ranger Dirt Day Shift",
      teamLabel: "Dirt",
      startsAt: "2027-07-04T16:00:00.000Z",
      endsAt: "2027-07-04T22:00:00.000Z",
      lifecycle: "active",
      capacity: 4,
    },
    {
      shiftId: swingShiftId,
      title: "Ranger Dirt Swing Shift",
      teamLabel: "Dirt",
      startsAt: "2027-07-04T22:00:00.000Z",
      endsAt: "2027-07-05T04:00:00.000Z",
      lifecycle: "upcoming",
      capacity: 3,
    },
  ],
  exceptions: [
    {
      id: "exception-coverage",
      severity: "warning",
      label: "Coverage gap",
      detail: "Day Shift is 1 below capacity with Vera Staff still scheduled.",
    },
    {
      id: "exception-equipment",
      severity: "attention",
      label: "Equipment still out",
      detail: "Radio 12 remains checked out to Local Field Author.",
    },
  ],
  assignments: [
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
      staffId: LOCAL_FIELD_FIXTURE.staffId,
      displayName: "Local Field Author",
      handle: "local-field-author",
      teamLabel: "Dirt",
      attendanceState: "checked_in",
      checkedInAt: "2027-07-04T15:52:00.000Z",
      currentDeploymentId: "deployment-gate-1",
      unscheduled: false,
    },
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
      staffId: "33333333-3333-4333-8333-333333333334",
      displayName: "Vera Staff",
      handle: "vera",
      teamLabel: "Dirt",
      attendanceState: "scheduled",
      checkedInAt: null,
      currentDeploymentId: null,
      unscheduled: false,
    },
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
      staffId: "33333333-3333-4333-8333-333333333335",
      displayName: "Sam Shiftlead",
      handle: "sam",
      teamLabel: "Dirt",
      attendanceState: "checked_in",
      checkedInAt: "2027-07-04T16:03:00.000Z",
      currentDeploymentId: "deployment-perimeter-north",
      unscheduled: false,
    },
  ],
  equipmentOut: [
    {
      checkoutId: "equipment-checkout-radio-12",
      itemName: "Radio 12",
      assetTag: "RDO-12",
      staffName: "Local Field Author",
      checkedOutAt: "2027-07-04T16:05:00.000Z",
    },
  ],
  deploymentOptions: [
    {
      deploymentId: "deployment-gate-1",
      name: "Gate 1",
      description: "Entry checkpoint",
      locationDetails: "North entry checkpoint",
    },
    {
      deploymentId: "deployment-perimeter-north",
      name: "Perimeter North",
      description: "Roving perimeter watch",
      locationDetails: "North fence line",
    },
    {
      deploymentId: "deployment-hq-runner",
      name: "HQ Runner",
      description: "Radio and supply runner",
      locationDetails: "Ranger HQ",
    },
  ],
  onSiteCount: 3,
  drillThrough: {
    logisticsRouteName: "events.departments.logistics",
    operationsRouteName: "events.departments.operations",
    planningRouteName: "events.departments.planning",
  },
};

export const LOCAL_LOGISTICS_DESK: LogisticsDeskModel = {
  context: LOCAL_DEPARTMENT_OPS_CONTEXT,
  selectedStaffId: null,
  selectedSearchContext: null,
  searchCache: {
    state: "offline_usable",
    scopeLabel: "Emberfall 2026 / Rangers",
    indexedAt: "2027-07-04T17:59:00.000Z",
    includes: ["staff", "equipment", "shift"],
    note: "Department-scoped cache available for staff, equipment, and shift lookup while offline.",
  },
  searchableStaff: [
    {
      staffId: LOCAL_FIELD_FIXTURE.staffId,
      displayName: "Local Field Author",
      handle: "local-field-author",
      teamLabel: "Dirt",
      presenceState: "on_site",
    },
    {
      staffId: "33333333-3333-4333-8333-333333333334",
      displayName: "Vera Staff",
      handle: "vera",
      teamLabel: "Dirt",
      presenceState: "off_site",
    },
    {
      staffId: "33333333-3333-4333-8333-333333333335",
      displayName: "Sam Shiftlead",
      handle: "sam",
      teamLabel: "Dirt",
      presenceState: "on_site",
    },
    {
      staffId: "33333333-3333-4333-8333-333333333336",
      displayName: "Ari Ranger",
      handle: "ari",
      teamLabel: "Dirt",
      presenceState: "on_site",
    },
  ],
  searchableEquipment: [
    {
      equipmentItemId: "equipment-radio-12",
      name: "Radio 12",
      assetTag: "RDO-12",
      status: "checked_out",
      holderName: "Local Field Author",
    },
    {
      equipmentItemId: "equipment-safety-vest",
      name: "Safety Vest",
      assetTag: "VEST-04",
      status: "available",
      holderName: null,
    },
    {
      equipmentItemId: "equipment-radio-13",
      name: "Radio 13",
      assetTag: "RDO-13",
      status: "available",
      holderName: null,
    },
    {
      equipmentItemId: "equipment-radio-14",
      name: "Radio 14",
      assetTag: "RDO-14",
      status: "available",
      holderName: null,
    },
    {
      equipmentItemId: "equipment-radio-15",
      name: "Radio 15",
      assetTag: "RDO-15",
      status: "available",
      holderName: null,
    },
  ],
  searchableShifts: LOCAL_DEPARTMENT_OVERVIEW.shifts,
  staffWorkspaces: {
    [LOCAL_FIELD_FIXTURE.staffId]: {
      staffId: LOCAL_FIELD_FIXTURE.staffId,
      displayName: "Local Field Author",
      handle: "local-field-author",
      teamLabel: "Dirt",
      presenceState: "on_site",
      canGoOffSite: false,
      offSiteBlockedReason:
        "Staff must be checked out of their shift and return equipment before going off-site.",
      shiftCards: [
        {
          shiftId: dayShiftId,
          title: "Ranger Dirt Day Shift",
          teamId: FIXTURE_RANGERS_DIRT_TEAM_ID,
          teamLabel: "Dirt",
          startsAt: "2027-07-04T16:00:00.000Z",
          endsAt: "2027-07-04T22:00:00.000Z",
          lifecycle: "active",
          attendanceState: "checked_in",
          assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
          canCheckIn: false,
          canCheckOut: true,
          canAddToShift: false,
        },
        {
          shiftId: swingShiftId,
          title: "Ranger Dirt Swing Shift",
          teamId: FIXTURE_RANGERS_DIRT_TEAM_ID,
          teamLabel: "Dirt",
          startsAt: "2027-07-04T22:00:00.000Z",
          endsAt: "2027-07-05T04:00:00.000Z",
          lifecycle: "upcoming",
          attendanceState: "scheduled",
          assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa91",
          canCheckIn: false,
          canCheckOut: false,
          canAddToShift: false,
        },
        {
          shiftId: overnightShiftId,
          title: "Ranger Command Overnight",
          teamId: LOCAL_FIELD_FIXTURE.teamId,
          teamLabel: "Command",
          startsAt: "2027-07-04T04:00:00.000Z",
          endsAt: "2027-07-04T10:00:00.000Z",
          lifecycle: "completed",
          attendanceState: "checked_out",
          assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaa92",
          canCheckIn: false,
          canCheckOut: false,
          canAddToShift: false,
        },
      ],
      openEquipment: [
        {
          checkoutId: "equipment-checkout-radio-12",
          equipmentItemId: "equipment-radio-12",
          name: "Radio 12",
          assetTag: "RDO-12",
          status: "checked_out",
          checkedOutAt: "2027-07-04T16:05:00.000Z",
        },
      ],
      availableEquipment: availableLogisticsEquipment,
      futureSignups: [
        {
          signupId: "signup-local-swing",
          shiftId: swingShiftId,
          shiftTitle: "Ranger Dirt Swing Shift",
          startsAt: "2027-07-04T22:00:00.000Z",
          endsAt: "2027-07-05T04:00:00.000Z",
          state: "signed_up",
        },
      ],
      provisionsExtensionNote:
        "Provisions will appear here once that domain is specified.",
    },
    "33333333-3333-4333-8333-333333333334": {
      staffId: "33333333-3333-4333-8333-333333333334",
      displayName: "Vera Staff",
      handle: "vera",
      teamLabel: "Dirt",
      presenceState: "off_site",
      canGoOffSite: true,
      offSiteBlockedReason: null,
      shiftCards: [
        {
          shiftId: dayShiftId,
          title: "Ranger Dirt Day Shift",
          teamId: FIXTURE_RANGERS_DIRT_TEAM_ID,
          teamLabel: "Dirt",
          startsAt: "2027-07-04T16:00:00.000Z",
          endsAt: "2027-07-04T22:00:00.000Z",
          lifecycle: "active",
          attendanceState: "scheduled",
          assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
          canCheckIn: false,
          canCheckOut: false,
          canAddToShift: false,
        },
      ],
      openEquipment: [],
      availableEquipment: availableLogisticsEquipment,
      futureSignups: [],
      provisionsExtensionNote:
        "Provisions will appear here once that domain is specified.",
    },
    "33333333-3333-4333-8333-333333333336": {
      staffId: "33333333-3333-4333-8333-333333333336",
      displayName: "Ari Ranger",
      handle: "ari",
      teamLabel: "Dirt",
      presenceState: "on_site",
      canGoOffSite: true,
      offSiteBlockedReason: null,
      shiftCards: [
        {
          shiftId: dayShiftId,
          title: "Ranger Dirt Day Shift",
          teamId: FIXTURE_RANGERS_DIRT_TEAM_ID,
          teamLabel: "Dirt",
          startsAt: "2027-07-04T16:00:00.000Z",
          endsAt: "2027-07-04T22:00:00.000Z",
          lifecycle: "active",
          attendanceState: null,
          assignmentId: null,
          canCheckIn: false,
          canCheckOut: false,
          canAddToShift: true,
        },
        {
          shiftId: swingShiftId,
          title: "Ranger Dirt Swing Shift",
          teamId: FIXTURE_RANGERS_DIRT_TEAM_ID,
          teamLabel: "Dirt",
          startsAt: "2027-07-04T22:00:00.000Z",
          endsAt: "2027-07-05T04:00:00.000Z",
          lifecycle: "upcoming",
          attendanceState: "scheduled",
          assignmentId: null,
          canCheckIn: false,
          canCheckOut: false,
          canAddToShift: false,
        },
      ],
      openEquipment: [],
      availableEquipment: availableLogisticsEquipment,
      futureSignups: [
        {
          signupId: "signup-ari-swing",
          shiftId: swingShiftId,
          shiftTitle: "Ranger Dirt Swing Shift",
          startsAt: "2027-07-04T22:00:00.000Z",
          endsAt: "2027-07-05T04:00:00.000Z",
          state: "signed_up",
        },
      ],
      provisionsExtensionNote:
        "Provisions will appear here once that domain is specified.",
    },
  },
};

export const LOCAL_OPERATIONS_CENTER: OperationsCenterModel = {
  context: LOCAL_DEPARTMENT_OPS_CONTEXT,
  capabilities: LOCAL_CAPABILITIES,
  modules: [
    {
      id: "deployments",
      title: "Deployments",
      available: true,
      unavailableReason: null,
      summary: "Current deployment/location assignments for staff on shift.",
    },
    {
      id: "field_reports",
      title: "Field Reports",
      available: true,
      unavailableReason: null,
      summary:
        "Field Report shortcuts available from the actor's existing permission.",
    },
    {
      id: "incidents",
      title: "Incidents",
      available: true,
      unavailableReason: null,
      summary: "Restricted IMS incident list/detail for IC-authorized operators.",
    },
    {
      id: "equipment",
      title: "Equipment",
      available: true,
      unavailableReason: null,
      summary: "1 item currently checked out in this department.",
    },
    {
      id: "maintenance",
      title: "Maintenance",
      available: false,
      unavailableReason:
        "Maintenance tickets are an extension point until that domain is specified.",
      summary: "No maintenance module yet.",
    },
  ],
  deploymentOptions: LOCAL_DEPARTMENT_OVERVIEW.deploymentOptions,
  deploymentRows: [
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
      staffId: LOCAL_FIELD_FIXTURE.staffId,
      displayName: "Local Field Author",
      shiftTitle: "Ranger Dirt Day Shift",
      currentDeploymentId: "deployment-gate-1",
    },
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
      staffId: "33333333-3333-4333-8333-333333333334",
      displayName: "Vera Staff",
      shiftTitle: "Ranger Dirt Day Shift",
      currentDeploymentId: null,
    },
    {
      assignmentId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
      staffId: "33333333-3333-4333-8333-333333333335",
      displayName: "Sam Shiftlead",
      shiftTitle: "Ranger Dirt Day Shift",
      currentDeploymentId: "deployment-perimeter-north",
    },
  ],
};

export const LOCAL_PLANNING_TABLE: PlanningTableModel = {
  context: LOCAL_DEPARTMENT_OPS_CONTEXT,
  selectedFilters: {
    teamId: null,
    date: null,
  },
  availableTeams: [
    {
      teamId: dirtTeamId,
      teamLabel: "Dirt",
    },
    {
      teamId: commandTeamId,
      teamLabel: "Command",
    },
  ],
  syncState: "offline",
  rows: [
    {
      shiftId: dayShiftId,
      title: "Ranger Dirt Day Shift",
      teamId: dirtTeamId,
      teamLabel: "Dirt",
      startsAt: "2027-07-04T16:00:00.000Z",
      endsAt: "2027-07-04T22:00:00.000Z",
      lifecycle: "active",
      capacity: 4,
      signedUpOrAssignedCount: 3,
      checkedInCount: 2,
      noShowCount: 0,
      unscheduledCount: 0,
      plannedHours: 24,
      actualHours: 4.2,
      varianceHours: -19.8,
      statusLabel: "Under target",
    },
    {
      shiftId: swingShiftId,
      title: "Ranger Dirt Swing Shift",
      teamId: dirtTeamId,
      teamLabel: "Dirt",
      startsAt: "2027-07-04T22:00:00.000Z",
      endsAt: "2027-07-05T04:00:00.000Z",
      lifecycle: "upcoming",
      capacity: 3,
      signedUpOrAssignedCount: 2,
      checkedInCount: 0,
      noShowCount: 0,
      unscheduledCount: 0,
      plannedHours: 18,
      actualHours: 0,
      varianceHours: -18,
      statusLabel: "Upcoming",
    },
    {
      shiftId: overnightShiftId,
      title: "Ranger Command Overnight",
      teamId: commandTeamId,
      teamLabel: "Command",
      startsAt: "2027-07-04T04:00:00.000Z",
      endsAt: "2027-07-04T10:00:00.000Z",
      lifecycle: "completed",
      capacity: null,
      signedUpOrAssignedCount: 2,
      checkedInCount: 2,
      noShowCount: 1,
      unscheduledCount: 1,
      plannedHours: 12,
      actualHours: 13.5,
      varianceHours: 1.5,
      statusLabel: "Completed over plan",
    },
  ],
};
