<?php

declare(strict_types=1);

namespace App\Orchid\Layouts\SharedWorkstationLoginCode;

use App\Models\SharedWorkstationLoginCode;
use App\Models\User;
use Orchid\Screen\Actions\Button;
use Orchid\Screen\Components\Cells\DateTimeSplit;
use Orchid\Screen\Layouts\Table;
use Orchid\Screen\TD;

/**
 * Outstanding and spent shared-workstation login codes (technical spec 13.2;
 * data/API 12.4).
 *
 * The code itself is not a column and cannot become one: only its keyed hash is
 * stored, raw codes are never logged, and 13.2 rules out printing or exporting
 * them as event prep sheets. What an operator identifies a code by is who it is
 * for, which workstation and event it works at, who generated it, and its state.
 *
 * Who generated it is the column that distinguishes the two authorities in
 * 13.2 without storing a third thing: a code whose generator is its own user was
 * generated by that person on their own device, and any other generator is a God
 * Mode operator acting for them.
 *
 * Used, expired, and revoked codes stay listed. An operator asking who could sign
 * in at a workstation is asking about credentials that existed.
 */
final class SharedWorkstationLoginCodeListLayout extends Table
{
    /**
     * @var string
     */
    public $target = 'login_codes';

    /**
     * @return TD[]
     */
    public function columns(): array
    {
        return [
            TD::make('user', __('User'))
                ->cantHide()
                ->render(function (SharedWorkstationLoginCode $code) {
                    $user = $code->user;

                    return $user instanceof User
                        ? e($user->name.' — '.$user->email)
                        : __('Unknown user');
                }),

            TD::make('shared_workstation', __('Workstation'))
                ->render(fn (SharedWorkstationLoginCode $code) => e(
                    (string) ($code->sharedWorkstation?->name ?? __('Unknown workstation'))
                )),

            TD::make('event', __('Event'))
                ->render(fn (SharedWorkstationLoginCode $code) => e(
                    (string) ($code->event?->name ?? __('Unknown event'))
                )),

            TD::make('generated_by', __('Generated by'))
                ->render(function (SharedWorkstationLoginCode $code) {
                    $generator = $code->generatedByUser;

                    if (! $generator instanceof User) {
                        return __('Unknown');
                    }

                    return $code->generated_by_user_id === $code->user_id
                        ? __('Self-service')
                        : e($generator->name);
                }),

            TD::make('status', __('Status'))
                ->render(fn (SharedWorkstationLoginCode $code) => $code->statusLabel()),

            TD::make('created_at', __('Generated'))
                ->usingComponent(DateTimeSplit::class)
                ->align(TD::ALIGN_RIGHT)
                ->sort(),

            TD::make('expires_at', __('Expires'))
                ->usingComponent(DateTimeSplit::class)
                ->align(TD::ALIGN_RIGHT)
                ->sort(),

            TD::make(__('Actions'))
                ->align(TD::ALIGN_CENTER)
                ->width('140px')
                ->render(fn (SharedWorkstationLoginCode $code) => Button::make(__('Revoke code'))
                    ->icon('bs.slash-circle')
                    ->confirm(__('Revoke this login code? It stops working at the workstation immediately and the user needs a new one. This is audited.'))
                    ->method('revokeCode', [
                        'login_code' => $code->getKey(),
                    ])
                    ->canSee($code->isActive())),
        ];
    }
}
