// What a surface says when the answer it needs is only ever the node's (M18.53;
// CLIENT-001, UI-020; technical spec 9.3; UI implementation contract 16.2).
//
// The offline surface audit holds every surface in the shared client to one of
// two outcomes: it renders from what this device is holding, or it says plainly
// that it needs a connection. This module is the second half. It is not a new
// error path — the seam already decides what a failed read means (M18.50) — it
// is the sentence, composed in one place so thirty surfaces cannot each invent
// a different way of saying the same thing.
//
// **Two failures, two answers.** A read fails in one of two ways and only one of
// them is about connectivity. A `MeridianApiError` is the node speaking: a
// refusal, a revoked token, a record that is not there. Its own words are what
// the reader should see, and `meridianErrorMessage` already prefers them.
// Anything else is a request that never completed, and there the surface's own
// fallback stands — which is what {@link connectionRequiredMessage} composes.
//
// **Why the sentence names a reason.** "Could not be read" tells somebody
// standing in a field that something went wrong and leaves them to guess whether
// to wait, walk toward the node, or give up. A surface that cannot work offline
// is not a defect (an export is generated by the node; a dashboard is compiled
// when it is asked for), but a reader is owed the difference between "this is
// broken" and "this one needs a connection, and here is why". The reasons are
// recorded beside the outcomes in `offlineSurfaceInventory.ts`.

import { MeridianApiError } from "@/api/meridianApi";

/**
 * Whether a failed read failed because nothing answered.
 *
 * The same test `meridianCachedJson` applies before it consults the store, and
 * for the same reason: a status means the node spoke, and a client that treated
 * a refusal as a connection problem would be inviting somebody to retry their
 * way past an answer the node already gave.
 */
export function nodeDidNotAnswer(error: unknown): boolean {
  return !(error instanceof MeridianApiError);
}

/**
 * The fallback a connection-required surface hands `meridianErrorMessage`.
 *
 * `subject` is what is unavailable, as the reader would name it. `reason` is why
 * this device cannot answer it alone, and it is a fact about the data rather
 * than about the network — the network is already in the first half of the
 * sentence.
 *
 * Composed rather than concatenated at each call site so the two halves stay in
 * the same order everywhere: what is missing, then why it could not be held.
 */
export function connectionRequiredMessage(
  subject: string,
  reason: string,
): string {
  return `${subject} could not be read: this device cannot reach a Meridian node, and ${reason}.`;
}
