<?php

namespace Tests\Feature;

use App\Models\ApiToken;
use App\Models\AuditEvent;
use App\Models\Device;
use App\Models\Event;
use App\Models\SharedWorkstation;
use App\Models\SharedWorkstationLoginCode;
use App\Models\User;
use App\Services\Auth\ApiLoginCodeGenerator;
use App\Services\Auth\ApiTokenIssuer;
use App\Services\Auth\SharedWorkstationLoginCodeGenerator;
use App\Services\Auth\SharedWorkstationLoginCodeService;
use App\Services\Auth\SharedWorkstationLoginException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Testing\TestResponse;
use Tests\TestCase;

/**
 * Shared-workstation login code generation, entry, rate limiting, and audit
 * (M16.8).
 *
 * Source: AUTH-026 through AUTH-029; technical spec 13.2; data/API 12.4. Codes
 * are generated by God mode for any known user and by a user for themselves from
 * a device where they already hold a session; they are scoped to one user, one
 * event, and one trusted shared workstation, are valid six weeks, are stored only
 * as keyed hashes, and are audited when generated and when used.
 *
 * The session a code establishes — technical spec 13.3 — is M16.9 and is not
 * asserted here beyond the rule that entry issues no API token.
 */
class SharedWorkstationLoginCodeTest extends TestCase
{
    use RefreshDatabase;

    private function service(): SharedWorkstationLoginCodeService
    {
        return app(SharedWorkstationLoginCodeService::class);
    }

    /**
     * A trusted shared workstation pinned to a real event, which is the only
     * state a code can be scoped to (technical spec 13.1).
     */
    private function workstation(array $attributes = []): SharedWorkstation
    {
        $event = Event::factory()->create();

        return SharedWorkstation::factory()->create([
            'organization_id' => $event->organization_id,
            'event_id' => $event->getKey(),
            ...$attributes,
        ]);
    }

    /**
     * A user holding a live API session, as a person's own phone does.
     */
    private function signedIn(User $user, ?Device $device = null): string
    {
        return app(ApiTokenIssuer::class)
            ->issue($user, $device ?? Device::factory()->create(), 'Meridian Field')
            ->plainTextToken;
    }

    private function requestCode(string $token, array $payload): TestResponse
    {
        $this->app['auth']->forgetGuards();

        return $this->withHeader('Authorization', 'Bearer '.$token)
            ->postJson(route('api.auth.shared-workstation-login-code.store'), $payload);
    }

    /**
     * Every stored audit row as text, for asserting what is in none of them.
     */
    private function auditText(): string
    {
        return AuditEvent::query()
            ->get()
            ->map(fn (AuditEvent $event): string => (string) json_encode($event->getAttributes()))
            ->implode("\n");
    }

    /*
    |--------------------------------------------------------------------------
    | Generation authority (AUTH-026, AUTH-028)
    |--------------------------------------------------------------------------
    */

    public function test_god_mode_generates_a_code_for_another_user(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();
        $operator = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, $operator, $workstation);

        $record = SharedWorkstationLoginCode::query()->sole();

        $this->assertSame($subject->getKey(), $record->user_id);
        $this->assertSame($operator->getKey(), $record->generated_by_user_id);
        $this->assertSame($workstation->getKey(), $record->shared_workstation_id);
        $this->assertSame($workstation->event_id, $record->event_id);
        $this->assertSame($record->getKey(), $issued->record->getKey());
    }

    public function test_a_user_generates_a_code_for_themselves_from_a_device_holding_a_session(): void
    {
        $workstation = $this->workstation();
        $user = User::factory()->create();
        $device = Device::factory()->create();

        $response = $this->requestCode($this->signedIn($user, $device), [
            'shared_workstation_id' => $workstation->getKey(),
        ]);

        $response->assertStatus(201);
        $response->assertJsonPath('user.id', $user->getKey());
        $response->assertJsonPath('shared_workstation.id', $workstation->getKey());
        $response->assertJsonPath('event_id', $workstation->event_id);

        $record = SharedWorkstationLoginCode::query()->sole();

        // AUTH-028: a self-service code is scoped to the generating user, which
        // is what `generated_by_user_id === user_id` records (data/API 12.4).
        $this->assertSame($user->getKey(), $record->user_id);
        $this->assertSame($user->getKey(), $record->generated_by_user_id);

        // The code that came back is the code that was stored, and the response
        // is the only place it exists.
        $code = (string) $response->json('code');
        $this->assertSame(SharedWorkstationLoginCodeGenerator::hash($code), $record->code_hash);
    }

    public function test_a_user_cannot_generate_a_code_for_someone_else(): void
    {
        $workstation = $this->workstation();
        $user = User::factory()->create();
        $someoneElse = User::factory()->create();

        $response = $this->requestCode($this->signedIn($user), [
            'shared_workstation_id' => $workstation->getKey(),
            'user_id' => $someoneElse->getKey(),
        ]);

        $response->assertStatus(403);
        $response->assertJsonPath('reason', SharedWorkstationLoginException::REASON_SELF_SERVICE_SCOPE);

        $this->assertSame(0, SharedWorkstationLoginCode::query()->count());
    }

    /**
     * The endpoint has no user field to abuse, and the domain refuses the same
     * thing independently, so a second caller cannot reintroduce it.
     */
    public function test_the_domain_refuses_self_service_generation_for_another_user(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();
        $other = User::factory()->create();

        try {
            $this->service()->generate(
                subject: $subject,
                generatedBy: $other,
                workstation: $workstation,
                authority: SharedWorkstationLoginCodeService::AUTHORITY_SELF_SERVICE,
            );
            $this->fail('Self-service generation for another user should be refused.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_SELF_SERVICE_SCOPE, $exception->reason);
        }

        $this->assertSame(0, SharedWorkstationLoginCode::query()->count());
    }

    public function test_generating_a_code_requires_a_session(): void
    {
        $workstation = $this->workstation();

        $this->postJson(route('api.auth.shared-workstation-login-code.store'), [
            'shared_workstation_id' => $workstation->getKey(),
        ])->assertUnauthorized();

        $this->assertSame(0, SharedWorkstationLoginCode::query()->count());
    }

    /*
    |--------------------------------------------------------------------------
    | Scope and validity (technical spec 13.2; data/API 12.4)
    |--------------------------------------------------------------------------
    */

    public function test_a_code_is_valid_for_six_weeks(): void
    {
        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            $this->workstation(),
        );

        $this->assertSame(
            now()->addWeeks(SharedWorkstationLoginCode::VALID_DURATION_WEEKS)->toDateString(),
            $issued->record->expires_at?->toDateString(),
        );
    }

    public function test_an_untrusted_or_revoked_workstation_is_refused_a_code(): void
    {
        foreach ([
            SharedWorkstation::factory()->untrusted(),
            SharedWorkstation::factory()->revoked(),
        ] as $state) {
            $event = Event::factory()->create();
            $workstation = $state->create([
                'organization_id' => $event->organization_id,
                'event_id' => $event->getKey(),
            ]);

            try {
                $this->service()->generateForUser(
                    User::factory()->create(),
                    User::factory()->create(),
                    $workstation,
                );
                $this->fail('An untrusted workstation should not be issued a login code.');
            } catch (SharedWorkstationLoginException $exception) {
                $this->assertSame(
                    SharedWorkstationLoginException::REASON_WORKSTATION_UNTRUSTED,
                    $exception->reason,
                );
            }
        }

        $this->assertSame(0, SharedWorkstationLoginCode::query()->count());
    }

    /**
     * A workstation whose pinned event this node does not hold has no event for a
     * code to be scoped to (technical spec 13.1).
     */
    public function test_a_workstation_without_a_resolvable_pinned_event_is_refused_a_code(): void
    {
        $workstation = SharedWorkstation::factory()->create();

        $response = $this->requestCode($this->signedIn(User::factory()->create()), [
            'shared_workstation_id' => $workstation->getKey(),
        ]);

        $response->assertStatus(409);
        $response->assertJsonPath('reason', SharedWorkstationLoginException::REASON_WORKSTATION_CONTEXT_UNPINNED);
        $this->assertSame(0, SharedWorkstationLoginCode::query()->count());
    }

    public function test_an_unknown_workstation_is_refused(): void
    {
        $response = $this->requestCode($this->signedIn(User::factory()->create()), [
            'shared_workstation_id' => (string) Str::uuid(),
        ]);

        $response->assertStatus(404);
        $response->assertJsonPath('reason', SharedWorkstationLoginException::REASON_WORKSTATION_UNKNOWN);
    }

    public function test_a_disabled_account_is_refused_a_code(): void
    {
        $this->expectException(SharedWorkstationLoginException::class);

        $this->service()->generateForUser(
            User::factory()->create(['disabled_at' => now()]),
            User::factory()->create(),
            $this->workstation(),
        );
    }

    /**
     * A new code for the same user and workstation replaces the one they held, so
     * a forgotten code does not leave a second six-week credential live.
     */
    public function test_generating_a_code_retires_the_users_outstanding_code_for_that_workstation(): void
    {
        $workstation = $this->workstation();
        $user = User::factory()->create();
        $operator = User::factory()->create();

        $first = $this->service()->generateForUser($user, $operator, $workstation)->record;
        $second = $this->service()->generateForUser($user, $operator, $workstation)->record;

        $this->assertNotNull($first->fresh()->revoked_at);
        $this->assertNull($second->fresh()->revoked_at);

        $audit = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_REVOKED)
            ->sole();

        $this->assertSame(SharedWorkstationLoginCodeService::REASON_SUPERSEDED, $audit->reason);
        $this->assertSame((string) $first->getKey(), $audit->entity_id);
    }

    public function test_a_code_for_another_workstation_is_left_alone(): void
    {
        $user = User::factory()->create();
        $operator = User::factory()->create();

        $atGate = $this->service()->generateForUser($user, $operator, $this->workstation())->record;
        $this->service()->generateForUser($user, $operator, $this->workstation());

        $this->assertNull($atGate->fresh()->revoked_at);
    }

    /*
    |--------------------------------------------------------------------------
    | Offline generation (AUTH-027)
    |--------------------------------------------------------------------------
    */

    /**
     * AUTH-027: self-service generation requires only reachability of the node
     * that will accept the code — no internet, no central node, no mail.
     */
    public function test_self_service_generation_needs_no_internet_central_node_or_mail(): void
    {
        // Any outbound HTTP call at all fails the test rather than being faked
        // into succeeding, and nothing may be mailed.
        Http::preventStrayRequests();
        Mail::fake();

        config()->set('meridian.node.central_url', null);

        $workstation = $this->workstation();
        $user = User::factory()->create();

        $this->requestCode($this->signedIn($user), [
            'shared_workstation_id' => $workstation->getKey(),
        ])->assertStatus(201);

        Mail::assertNothingOutgoing();
        $this->assertSame(1, SharedWorkstationLoginCode::query()->count());
    }

    /*
    |--------------------------------------------------------------------------
    | Rate limiting (AUTH-029)
    |--------------------------------------------------------------------------
    */

    public function test_generation_is_rate_limited_per_user(): void
    {
        config()->set('meridian.shared_workstation_login_codes.generation_per_user_per_hour', 2);

        $workstation = $this->workstation();
        $user = User::factory()->create();
        $token = $this->signedIn($user);

        $this->requestCode($token, ['shared_workstation_id' => $workstation->getKey()])->assertStatus(201);
        $this->requestCode($token, ['shared_workstation_id' => $workstation->getKey()])->assertStatus(201);

        $refused = $this->requestCode($token, ['shared_workstation_id' => $workstation->getKey()]);

        $refused->assertStatus(429);
        $refused->assertJsonPath('reason', SharedWorkstationLoginException::REASON_RATE_LIMITED);
        $refused->assertHeader('Retry-After');

        // The limit is keyed to the user a code is for, so a second person is
        // unaffected by the first person's burst.
        $this->requestCode($this->signedIn(User::factory()->create()), [
            'shared_workstation_id' => $workstation->getKey(),
        ])->assertStatus(201);
    }

    public function test_generation_is_rate_limited_per_node(): void
    {
        config()->set('meridian.shared_workstation_login_codes.generation_per_node_per_hour', 2);

        $workstation = $this->workstation();
        $operator = User::factory()->create();

        $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);
        $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);

        try {
            $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);
            $this->fail('The node-wide generation limit should have refused a third code.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_RATE_LIMITED, $exception->reason);
        }

        $this->assertSame(2, SharedWorkstationLoginCode::query()->count());
    }

    public function test_code_entry_is_rate_limited_per_workstation(): void
    {
        config()->set('meridian.shared_workstation_login_codes.entry_attempts_per_workstation_per_minute', 2);

        $workstation = $this->workstation();
        $other = $this->workstation();

        foreach (['WRONGCOD', 'WRONGCDE'] as $guess) {
            try {
                $this->service()->redeem($workstation, $guess);
            } catch (SharedWorkstationLoginException $exception) {
                $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
            }
        }

        try {
            $this->service()->redeem($workstation, 'WRONGCDF');
            $this->fail('A third attempt at this workstation should have been rate limited.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_RATE_LIMITED, $exception->reason);
        }

        // Guessing at one workstation does not lock out another.
        try {
            $this->service()->redeem($other, 'WRONGCDG');
            $this->fail('An unknown code should be refused.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
        }
    }

    /*
    |--------------------------------------------------------------------------
    | Code entry (technical spec 13.2; data/API 12.4)
    |--------------------------------------------------------------------------
    */

    public function test_a_code_signs_in_the_user_it_was_generated_for_and_is_then_spent(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, User::factory()->create(), $workstation);

        // Typed as a person types it: with the presentation dash, in lower case.
        $redeemed = $this->service()->redeem($workstation, strtolower($issued->formattedCode()));

        $this->assertSame($subject->getKey(), $redeemed->user_id);
        $this->assertNotNull($redeemed->used_at);

        try {
            $this->service()->redeem($workstation, $issued->plaintextCode);
            $this->fail('A used code should not sign anybody in again.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
        }
    }

    /**
     * A code held by someone who has since been disabled does not sign them in.
     * The code is spent rather than handed back, as the mailed API login code is:
     * the refusal is about the account, not about possession of the code.
     */
    public function test_a_code_for_a_since_disabled_account_does_not_sign_anybody_in(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, User::factory()->create(), $workstation);

        $subject->forceFill(['disabled_at' => now()])->save();

        try {
            $this->service()->redeem($workstation, $issued->plaintextCode);
            $this->fail('A disabled account should not be signed in by a code.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_ACCOUNT_DISABLED, $exception->reason);
        }

        $this->assertNotNull($issued->record->fresh()->used_at);
        $this->assertSame(0, AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_USED)
            ->count());
    }

    public function test_a_code_does_not_work_at_another_workstation(): void
    {
        $workstation = $this->workstation();
        $elsewhere = $this->workstation();

        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            $workstation,
        );

        $this->expectException(SharedWorkstationLoginException::class);

        $this->service()->redeem($elsewhere, $issued->plaintextCode);
    }

    public function test_an_expired_or_revoked_code_does_not_sign_anybody_in(): void
    {
        $workstation = $this->workstation();
        $operator = User::factory()->create();

        $expiring = $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);

        $this->travel(SharedWorkstationLoginCode::VALID_DURATION_WEEKS + 1)->weeks();

        try {
            $this->service()->redeem($workstation, $expiring->plaintextCode);
            $this->fail('An expired code should not sign anybody in.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
        }

        $revoked = $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);
        $this->assertTrue($this->service()->revoke($revoked->record, $operator));

        try {
            $this->service()->redeem($workstation, $revoked->plaintextCode);
            $this->fail('A revoked code should not sign anybody in.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
        }
    }

    /**
     * Data/API 12.4: a successful code entry establishes a shared workstation
     * session and does not issue an API token under 12.5. The session itself is
     * M16.9; that no token appears is decided here.
     */
    public function test_code_entry_issues_no_api_token(): void
    {
        $workstation = $this->workstation();

        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            $workstation,
        );

        $before = ApiToken::query()->count();

        $this->service()->redeem($workstation, $issued->plaintextCode);

        $this->assertSame($before, ApiToken::query()->count());
    }

    /*
    |--------------------------------------------------------------------------
    | Audit (data/API section 8, 12.4; technical spec 13.2)
    |--------------------------------------------------------------------------
    */

    public function test_generation_is_audited_with_its_authority_scope_and_actor(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();
        $operator = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, $operator, $workstation);

        $audit = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_GENERATED)
            ->sole();

        $this->assertSame((string) $issued->record->getKey(), $audit->entity_id);
        $this->assertSame($operator->getKey(), $audit->actor_user_id);
        $this->assertSame(SharedWorkstationLoginCodeService::AUTHORITY_GOD_MODE, $audit->reason);
        $this->assertSame($workstation->organization_id, $audit->organization_id);
        $this->assertSame($workstation->event_id, $audit->event_id);
        $this->assertSame($subject->getKey(), $audit->after_json['user_id']);
        $this->assertSame((string) $workstation->getKey(), $audit->after_json['shared_workstation_id']);
    }

    public function test_self_service_generation_is_audited_against_the_device_that_holds_the_session(): void
    {
        $workstation = $this->workstation();
        $user = User::factory()->create();
        $device = Device::factory()->create();

        $this->requestCode($this->signedIn($user, $device), [
            'shared_workstation_id' => $workstation->getKey(),
        ])->assertStatus(201);

        $audit = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_GENERATED)
            ->sole();

        $this->assertSame($user->getKey(), $audit->actor_user_id);
        $this->assertSame((string) $device->getKey(), $audit->actor_device_id);
        $this->assertSame(SharedWorkstationLoginCodeService::AUTHORITY_SELF_SERVICE, $audit->reason);
        $this->assertSame(AuditEvent::SOURCE_API, $audit->source_context);
    }

    public function test_using_a_code_is_audited_as_the_user_it_signed_in(): void
    {
        $workstation = $this->workstation();
        $subject = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, User::factory()->create(), $workstation);

        $this->service()->redeem($workstation, $issued->plaintextCode);

        $audit = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_USED)
            ->sole();

        $this->assertSame((string) $issued->record->getKey(), $audit->entity_id);
        $this->assertSame($subject->getKey(), $audit->actor_user_id);
        $this->assertSame((string) $workstation->device_id, $audit->actor_device_id);
        $this->assertSame($workstation->event_id, $audit->event_id);
    }

    /**
     * Technical spec 13.2: failed login-code attempts are audited after a
     * threshold. One mistyped character at a busy kiosk is not an audit entry.
     */
    public function test_failed_code_entry_is_audited_only_after_the_threshold(): void
    {
        config()->set('meridian.shared_workstation_login_codes.failed_entry_audit_threshold', 2);
        config()->set('meridian.shared_workstation_login_codes.entry_attempts_per_workstation_per_minute', 10);

        $workstation = $this->workstation();

        $this->attemptAndFail($workstation, 'WRONGCOD');

        $this->assertSame(0, AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_ENTRY_FAILED)
            ->count());

        $this->attemptAndFail($workstation, 'WRONGCDE');

        $audit = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_ENTRY_FAILED)
            ->sole();

        $this->assertSame((string) $workstation->getKey(), $audit->entity_id);
        $this->assertSame(2, $audit->after_json['failed_attempts']);
    }

    public function test_a_successful_entry_clears_the_workstations_failure_count(): void
    {
        config()->set('meridian.shared_workstation_login_codes.failed_entry_audit_threshold', 2);
        config()->set('meridian.shared_workstation_login_codes.entry_attempts_per_workstation_per_minute', 10);

        $workstation = $this->workstation();
        $operator = User::factory()->create();

        $issued = $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);

        $this->attemptAndFail($workstation, 'WRONGCOD');
        $this->service()->redeem($workstation, $issued->plaintextCode);
        $this->attemptAndFail($workstation, 'WRONGCDE');

        // The wrong code after the successful sign-in is the first of a new
        // window rather than the second of the old one.
        $this->assertSame(0, AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_ENTRY_FAILED)
            ->count());
    }

    /*
    |--------------------------------------------------------------------------
    | Redaction (technical spec 13.2; data/API 12.4)
    |--------------------------------------------------------------------------
    */

    /**
     * "Raw login codes are not logged" (data/API 12.4). The plaintext exists in
     * the response that generated it and nowhere else — not in the row, not in an
     * audit entry, not in the log.
     */
    public function test_no_raw_code_reaches_the_database_an_audit_entry_or_the_log(): void
    {
        Log::spy();

        $workstation = $this->workstation();
        $user = User::factory()->create();

        $response = $this->requestCode($this->signedIn($user), [
            'shared_workstation_id' => $workstation->getKey(),
        ])->assertStatus(201);

        $formatted = (string) $response->json('code');
        $normalized = SharedWorkstationLoginCodeGenerator::normalize($formatted);

        $record = SharedWorkstationLoginCode::query()->sole();

        // Reach the rest of a code's audited life before asserting.
        $this->service()->redeem($workstation, $formatted);

        $storedRow = (string) json_encode($record->fresh()?->getAttributes());
        $audited = $this->auditText();

        $this->assertNotSame('', $audited);

        foreach ([$storedRow, $audited] as $haystack) {
            $this->assertStringNotContainsString($formatted, $haystack);
            $this->assertStringNotContainsString($normalized, $haystack);
        }

        // Not even the stored hash reaches an audit entry: entries name the code
        // by identifier and by scope.
        $this->assertStringNotContainsString($record->code_hash, $audited);
        $this->assertStringContainsString((string) $record->getKey(), $audited);

        Log::shouldNotHaveReceived('info');
        Log::shouldNotHaveReceived('debug');
        Log::shouldNotHaveReceived('warning');
        Log::shouldNotHaveReceived('error');
    }

    public function test_only_a_keyed_hash_of_a_code_is_stored(): void
    {
        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            $this->workstation(),
        );

        $record = SharedWorkstationLoginCode::query()->sole();

        $this->assertNotSame($issued->plaintextCode, $record->code_hash);
        $this->assertSame(
            SharedWorkstationLoginCodeGenerator::hash($issued->plaintextCode),
            $record->code_hash,
        );

        // Keyed to this application, so a stolen table cannot be turned into a
        // rainbow table, and namespaced away from the API login code hash so a
        // hash cannot be carried between the two credentials.
        $this->assertNotSame(
            hash('sha256', $issued->plaintextCode),
            $record->code_hash,
        );
        $this->assertNotSame(
            ApiLoginCodeGenerator::hash($issued->plaintextCode),
            $record->code_hash,
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Untargeted codes (M18.58; AUTH-031; technical spec 13.2, Untargeted codes)
    |--------------------------------------------------------------------------
    */

    public function test_an_unbound_code_redeems_at_any_trusted_workstation_pinned_to_its_event(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();

        // A second trusted workstation pinned to the same event, which the code
        // never named and may still be redeemed at.
        $other = SharedWorkstation::factory()->create([
            'organization_id' => $event->organization_id,
            'event_id' => $event->getKey(),
        ]);

        $subject = User::factory()->create();

        $issued = $this->service()->generateForUser($subject, User::factory()->create(), null, $event);

        $this->assertNull($issued->record->shared_workstation_id);
        $this->assertSame($event->getKey(), $issued->record->event_id);

        $redeemed = $this->service()->redeem($other, $issued->plaintextCode);

        $this->assertSame($subject->getKey(), $redeemed->user_id);
    }

    public function test_an_unbound_code_is_refused_at_a_workstation_pinned_to_a_different_event(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();

        $elsewhere = $this->workstation(); // its own event

        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            null,
            $event,
        );

        $this->attemptAndFail($elsewhere, $issued->plaintextCode);

        $this->assertNull($issued->record->fresh()->used_at);
    }

    public function test_redeeming_an_unbound_code_stamps_the_workstation_and_spends_it(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();

        $other = SharedWorkstation::factory()->create([
            'organization_id' => $event->organization_id,
            'event_id' => $event->getKey(),
        ]);

        $issued = $this->service()->generateForUser(
            User::factory()->create(),
            User::factory()->create(),
            null,
            $event,
        );

        $this->service()->redeem($workstation, $issued->plaintextCode);

        // The record now says where the code was actually used (AUTH-031).
        $record = $issued->record->fresh();
        $this->assertSame((string) $workstation->getKey(), (string) $record->shared_workstation_id);
        $this->assertNotNull($record->used_at);

        // Spent means spent everywhere, including at the sibling workstation.
        $this->attemptAndFail($other, $issued->plaintextCode);
    }

    public function test_an_unbound_code_needs_an_event(): void
    {
        try {
            $this->service()->generateForUser(
                User::factory()->create(),
                User::factory()->create(),
                null,
                null,
            );
            $this->fail('An unbound code with no event should be refused.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_EVENT_CONTEXT_MISSING, $exception->reason);
        }
    }

    public function test_an_unbound_code_replaces_the_users_outstanding_unbound_code_for_the_event(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();
        $subject = User::factory()->create();
        $operator = User::factory()->create();

        $first = $this->service()->generateForUser($subject, $operator, null, $event);
        $second = $this->service()->generateForUser($subject, $operator, null, $event);

        $this->assertNotNull($first->record->fresh()->revoked_at);
        $this->assertNull($second->record->fresh()->revoked_at);
    }

    public function test_a_user_generates_an_unbound_code_for_themselves_over_the_api(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();
        $user = User::factory()->create();

        $response = $this->requestCode($this->signedIn($user), [
            'event_id' => $event->getKey(),
        ]);

        $response->assertStatus(201)
            ->assertJsonPath('shared_workstation', null)
            ->assertJsonPath('event_id', $event->getKey());

        $record = SharedWorkstationLoginCode::query()->sole();
        $this->assertNull($record->shared_workstation_id);

        // And the code it returned works at a trusted workstation pinned to
        // that event.
        $code = (string) $response->json('code');
        $redeemed = $this->service()->redeem($workstation, $code);
        $this->assertSame($user->getKey(), $redeemed->user_id);
    }

    public function test_an_api_request_naming_neither_workstation_nor_event_is_refused(): void
    {
        $response = $this->requestCode($this->signedIn(User::factory()->create()), []);

        $response->assertStatus(422)
            ->assertJsonPath('reason', SharedWorkstationLoginException::REASON_EVENT_CONTEXT_MISSING);
    }

    /**
     * AUTH-031: the audit entry for a use names the redeeming workstation for
     * both kinds of code, which is the property that makes the looser scope
     * reviewable afterwards.
     */
    public function test_the_use_audit_names_the_redeeming_workstation_for_both_kinds(): void
    {
        $workstation = $this->workstation();
        $event = $workstation->event()->firstOrFail();
        $operator = User::factory()->create();

        $targeted = $this->service()->generateForUser(User::factory()->create(), $operator, $workstation);
        $this->service()->redeem($workstation, $targeted->plaintextCode);

        $unbound = $this->service()->generateForUser(User::factory()->create(), $operator, null, $event);
        $this->service()->redeem($workstation, $unbound->plaintextCode);

        $entries = AuditEvent::query()
            ->where('action', SharedWorkstationLoginCodeService::AUDIT_USED)
            ->orderBy('created_at')
            ->get();

        $this->assertCount(2, $entries);

        foreach ($entries as $entry) {
            $this->assertSame(
                (string) $workstation->getKey(),
                (string) $entry->after_json['shared_workstation_id'],
            );
        }
    }

    private function attemptAndFail(SharedWorkstation $workstation, string $guess): void
    {
        try {
            $this->service()->redeem($workstation, $guess);
            $this->fail('An unknown code should be refused.');
        } catch (SharedWorkstationLoginException $exception) {
            $this->assertSame(SharedWorkstationLoginException::REASON_INVALID_CODE, $exception->reason);
        }
    }
}
