<script setup lang="ts">
import { computed, ref } from "vue";

import EventCredentialSection from "@/components/sections/EventCredentialSection.vue";
import WorkflowPageShell from "@/components/WorkflowPageShell.vue";
import { meridianErrorMessage } from "@/api/meridianApi";
import { credentialAdminAuthority } from "@/credentials/eventCredentialAdminModel";
import { useConnectivity } from "@/offline/useConnectivity";
import {
  CREDENTIAL_ELIGIBILITY_EXPORT,
  downloadReportingExport,
  reportingExportAuthorityFor,
  type ReportingExportDescriptor,
} from "@/reporting/reportingExports";
import { sessionOrganizationLabel } from "@/session/sessionContext";

/**
 * `organizer.credentials` — event credential administration (M18.5; CRED-009
 * through CRED-014) and the credential eligibility export entry point (M16.22;
 * REPORT-001, REPORT-015; CLIENT-019, CLIENT-023; UI contract 12.6).
 *
 * Two featuresets over the same records, and they are gated separately because
 * they are separate authorities. `reports.credential_eligibility.export` is held
 * by department leads for their own department (REPORT-007);
 * `event.credentials.revoke` is held by organizers and Incident Command leads
 * for the whole event (CRED-011). A department lead lands here and sees an
 * export; an Incident Command lead lands here and sees the list and no export.
 * Neither is offered the other half, and neither is shown a disabled control
 * standing in for it (CLIENT-005).
 *
 * What the export owes a reader before they run it is the scope and the
 * exclusions (REPORT-014). Both are stated rather than predicted: the node
 * resolves the scope from the caller's own authority when it issues the URL and
 * again when it serves the file, so the surface names the rule and the roles it
 * is being applied to instead of guessing at the row count.
 */
/**
 * One export, and only one (M18.25).
 *
 * M18.25 gave the other four Alpha 1 exports a descriptor and a download path,
 * so "every export this caller may run" is now five entries rather than one.
 * This page is not where they belong: it is a page about event credentials, and
 * the export it offers is the one that reads those records. The other four are
 * offered by the export surfaces of M18.26. A caller holding, say, hours
 * worked and not credential eligibility therefore has no export featureset here
 * at all rather than a page of exports about something else.
 */
const authority = reportingExportAuthorityFor([CREDENTIAL_ELIGIBILITY_EXPORT]);
const credentialAdmin = credentialAdminAuthority;
const connectivity = useConnectivity();

/**
 * Exports are generated by the node, so there is nothing to run without one.
 *
 * Refused where it stands rather than queued: an export is not a command and
 * the outbox has nothing to replay (data/API 7.2, technical spec 19.2).
 */
const isOfflineBlocked = computed(() => connectivity.value !== "online");

const error = ref<string | null>(null);
const notice = ref<string | null>(null);
const busyExportId = ref<string | null>(null);

const eyebrow = "Organizer administration";

/** Whether either featureset on this page admits this user. */
const hasAnyAuthority = computed(
  () => authority.value !== null || credentialAdmin.value !== null,
);

/**
 * The lede names the event and the standing that reached it.
 *
 * Whichever authority answered is the one it names, because that is the one the
 * page's contents came from. An Incident Command lead is not told they exported
 * anything, and a department lead is not told they administer credentials.
 */
const lede = computed(() => {
  const admin = credentialAdmin.value;

  if (admin !== null) {
    return `${admin.eventLabel} — administered as ${admin.roleLabel}.`;
  }

  const event = authority.value;

  if (event === null) {
    return sessionOrganizationLabel.value ?? "";
  }

  return `${event.eventLabel} — exported as ${event.roleLabel}.`;
});

/**
 * Run one export (CLIENT-019, CLIENT-020).
 *
 * The endpoint comes off the descriptor that was rendered, so the button runs
 * the export it is labelled with. No `department_id` is sent: the caller's own
 * scope is what the endpoint resolves by default, and narrowing belongs to
 * `organizer.exports`, which carries the department picker that drives it. This
 * page is about one event's credentials and exports them at the scope the caller
 * already holds.
 */
async function runExport(descriptor: ReportingExportDescriptor): Promise<void> {
  const event = authority.value;

  if (event === null || isOfflineBlocked.value) {
    return;
  }

  error.value = null;
  notice.value = null;
  busyExportId.value = descriptor.id;

  try {
    const issued = await downloadReportingExport(descriptor, event.eventId);

    notice.value =
      issued.expiresAt === null
        ? `${descriptor.label} is downloading.`
        : `${descriptor.label} is downloading. The link expires at ${formatExpiry(issued.expiresAt)}.`;
  } catch (caught) {
    error.value = meridianErrorMessage(
      caught,
      "Unable to export credential eligibility. Check the connection to this node and try again.",
    );
  } finally {
    busyExportId.value = null;
  }
}

/** The moment a link stops working, in the reader's own time zone. */
function formatExpiry(expiresAt: string): string {
  const moment = new Date(expiresAt);

  return Number.isNaN(moment.getTime())
    ? expiresAt
    : moment.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
}
</script>

<template>
  <WorkflowPageShell
    heading-id="organizer-credentials-heading"
    title="Credentials"
    :eyebrow="eyebrow"
    :lede="lede"
  >
    <!--
      Absent, not disabled: a client whose session carries neither capability
      here, or no event to apply one to, has nothing this page can offer
      (CLIENT-005). The server refuses the request either way (CLIENT-006).
    -->
    <p
      v-if="!hasAnyAuthority"
      class="credentials__restricted"
      role="status"
    >
      Event credential administration requires organizer or Incident Command
      lead authority, and the eligibility export requires organizer or
      department lead authority, for an event this device is working in.
    </p>

    <template v-else>
      <!--
        The list first. Somebody who arrives with a person in mind is here to
        act on them; the export is the thing you leave with, not the thing you
        came for.
      -->
      <EventCredentialSection
        v-if="credentialAdmin"
        variant="section"
        :event-id="credentialAdmin.eventId"
        :event-label="credentialAdmin.eventLabel"
      />

      <template v-if="authority">
        <p v-if="isOfflineBlocked" class="credentials__hint" role="status">
          Exports are generated by the node and require a server connection. They
          are not queued for later.
        </p>

        <p v-if="error" class="credentials__error" role="alert">{{ error }}</p>

        <p v-if="notice" class="credentials__notice" role="status">
          {{ notice }}
        </p>

        <article
          v-for="descriptor in authority.exports"
          :key="descriptor.id"
          class="credentials__export"
        >
          <header class="credentials__export-header">
            <h2 class="credentials__export-title">{{ descriptor.label }}</h2>
            <button
              type="button"
              class="credentials__download"
              :disabled="isOfflineBlocked || busyExportId === descriptor.id"
              @click="runExport(descriptor)"
            >
              {{
                busyExportId === descriptor.id
                  ? "Preparing…"
                  : `Export ${descriptor.format}`
              }}
            </button>
          </header>

          <p class="credentials__export-contains">{{ descriptor.contains }}</p>

          <!--
            Scope and exclusions before generation (REPORT-010, REPORT-014). The
            scope is the rule the node applies, not a prediction of its outcome.
          -->
          <dl class="credentials__facts">
            <div class="credentials__fact">
              <dt>Scope</dt>
              <dd>
                {{ authority.eventLabel }}. An organizer exports every
                department in the event; a department role exports its own
                department.
              </dd>
            </div>
            <div class="credentials__fact">
              <dt>Excluded</dt>
              <dd>{{ descriptor.excludes.join(", ") }}.</dd>
            </div>
            <div class="credentials__fact">
              <dt>Columns</dt>
              <dd class="credentials__columns">
                {{ descriptor.columns.join(", ") }}
              </dd>
            </div>
          </dl>

          <p class="credentials__export-note">
            The file downloads through a short-lived link scoped to this export
            and to you. Generating it is recorded in the audit log.
          </p>
        </article>
      </template>
    </template>
  </WorkflowPageShell>
</template>

<style scoped>
.credentials__restricted,
.credentials__hint,
.credentials__error,
.credentials__notice {
  margin: 0;
  padding: var(--m-space-3);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
}

.credentials__error {
  border-color: color-mix(
    in srgb,
    var(--m-status-danger, #cc792f) 40%,
    var(--m-border-default)
  );
  color: var(--m-status-danger, #cc792f);
}

.credentials__export {
  display: grid;
  gap: var(--m-space-3);
  padding: var(--m-space-4);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
  background: var(--m-surface-raised);
}

.credentials__export-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: var(--m-space-3);
}

.credentials__export-title {
  margin: 0;
  font-family: var(--m-font-heading);
  font-size: var(--m-text-lg);
}

.credentials__download {
  display: inline-flex;
  align-items: center;
  min-height: 2.75rem;
  padding: 0 var(--m-space-4);
  border: 1px solid transparent;
  border-radius: var(--m-radius-sm);
  background: var(--m-action-primary-bg);
  color: var(--m-action-primary-text);
  font: inherit;
  font-weight: 600;
  cursor: pointer;
}

.credentials__download:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.credentials__export-contains,
.credentials__export-note {
  margin: 0;
}

.credentials__export-note {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
}

.credentials__facts {
  display: grid;
  gap: var(--m-space-2);
  margin: 0;
}

.credentials__fact {
  display: grid;
  grid-template-columns: minmax(5rem, 8rem) 1fr;
  gap: var(--m-space-3);
}

.credentials__fact dt {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
  font-weight: 600;
}

.credentials__fact dd {
  margin: 0;
}

.credentials__columns {
  overflow-wrap: anywhere;
  font-family: var(--m-font-mono, monospace);
  font-size: var(--m-text-sm);
}

@media (max-width: 40rem) {
  .credentials__fact {
    grid-template-columns: 1fr;
    gap: var(--m-space-1);
  }
}
</style>
