<script setup lang="ts">
import { computed, ref } from "vue";

import WorkflowPageShell from "@/components/WorkflowPageShell.vue";
import { meridianErrorMessage } from "@/api/meridianApi";
import { useConnectivity } from "@/offline/useConnectivity";
import {
  downloadReportingExport,
  reportingExportAuthority,
  type ReportingExportDescriptor,
} from "@/reporting/reportingExports";
import { sessionOrganizationLabel } from "@/session/sessionContext";

/**
 * `organizer.credentials` — the event credential surface, and the entry point
 * that runs the credential eligibility export (M16.22; REPORT-001, REPORT-015;
 * CLIENT-019, CLIENT-023; UI contract 12.6).
 *
 * The export is all this page does today. Credential administration proper —
 * listing an event's credentials and revoking one — is M18.5, which builds on
 * `CredentialRevocationService` and a `revoke-credential` command that does not
 * exist yet; a control with nothing behind it is one CLIENT-006 says not to
 * render, so there is none here.
 *
 * What the page owes a reader before they run anything is the scope and the
 * exclusions (REPORT-014). Both are stated rather than predicted: the node
 * resolves the scope from the caller's own authority when it issues the URL and
 * again when it serves the file, so the surface names the rule and the roles it
 * is being applied to instead of guessing at the row count.
 */
const authority = reportingExportAuthority;
const connectivity = useConnectivity();

/**
 * Exports are generated by the node, so there is nothing to run without one.
 *
 * Refused where it stands rather than queued: an export is not a command and
 * the outbox has nothing to replay (data/API 7.2, technical spec 19.2).
 */
const isOfflineBlocked = computed(() => connectivity.value !== "online");

const error = ref<string | null>(null);
const notice = ref<string | null>(null);
const busyExportId = ref<string | null>(null);

const eyebrow = "Organizer administration";
const lede = computed(() => {
  const event = authority.value;

  if (event === null) {
    return sessionOrganizationLabel.value ?? "";
  }

  return `${event.eventLabel} — exported as ${event.roleLabel}.`;
});

/**
 * Run one export (CLIENT-019, CLIENT-020).
 *
 * The endpoint comes off the descriptor that was rendered, so the button runs
 * the export it is labelled with. No `department_id` is sent: the caller's own
 * scope is what the endpoint resolves by default, and narrowing is a control the
 * reporting surfaces of M18.26 add along with the department picker to drive it.
 */
async function runExport(descriptor: ReportingExportDescriptor): Promise<void> {
  const event = authority.value;

  if (event === null || isOfflineBlocked.value) {
    return;
  }

  error.value = null;
  notice.value = null;
  busyExportId.value = descriptor.id;

  try {
    const issued = await downloadReportingExport(descriptor, event.eventId);

    notice.value =
      issued.expiresAt === null
        ? `${descriptor.label} is downloading.`
        : `${descriptor.label} is downloading. The link expires at ${formatExpiry(issued.expiresAt)}.`;
  } catch (caught) {
    error.value = meridianErrorMessage(
      caught,
      "Unable to export credential eligibility. Check the connection to this node and try again.",
    );
  } finally {
    busyExportId.value = null;
  }
}

/** The moment a link stops working, in the reader's own time zone. */
function formatExpiry(expiresAt: string): string {
  const moment = new Date(expiresAt);

  return Number.isNaN(moment.getTime())
    ? expiresAt
    : moment.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
}
</script>

<template>
  <WorkflowPageShell
    heading-id="organizer-credentials-heading"
    title="Credentials"
    :eyebrow="eyebrow"
    :lede="lede"
  >
    <!--
      Absent, not disabled: a client whose session carries no export capability
      here, or no event to export for, has nothing this page can offer
      (CLIENT-005). The server refuses the request either way (CLIENT-006).
    -->
    <p v-if="authority === null" class="credentials__restricted" role="status">
      Credential eligibility export requires organizer or department lead
      authority for an event this device is working in.
    </p>

    <template v-else>
      <p v-if="isOfflineBlocked" class="credentials__hint" role="status">
        Exports are generated by the node and require a server connection. They
        are not queued for later.
      </p>

      <p v-if="error" class="credentials__error" role="alert">{{ error }}</p>

      <p v-if="notice" class="credentials__notice" role="status">
        {{ notice }}
      </p>

      <article
        v-for="descriptor in authority.exports"
        :key="descriptor.id"
        class="credentials__export"
      >
        <header class="credentials__export-header">
          <h2 class="credentials__export-title">{{ descriptor.label }}</h2>
          <button
            type="button"
            class="credentials__download"
            :disabled="isOfflineBlocked || busyExportId === descriptor.id"
            @click="runExport(descriptor)"
          >
            {{
              busyExportId === descriptor.id
                ? "Preparing…"
                : `Export ${descriptor.format}`
            }}
          </button>
        </header>

        <p class="credentials__export-contains">{{ descriptor.contains }}</p>

        <!--
          Scope and exclusions before generation (REPORT-010, REPORT-014). The
          scope is the rule the node applies, not a prediction of its outcome.
        -->
        <dl class="credentials__facts">
          <div class="credentials__fact">
            <dt>Scope</dt>
            <dd>
              {{ authority.eventLabel }}. An organizer exports every department
              in the event; a department role exports its own department.
            </dd>
          </div>
          <div class="credentials__fact">
            <dt>Excluded</dt>
            <dd>{{ descriptor.excludes.join(", ") }}.</dd>
          </div>
          <div class="credentials__fact">
            <dt>Columns</dt>
            <dd class="credentials__columns">
              {{ descriptor.columns.join(", ") }}
            </dd>
          </div>
        </dl>

        <p class="credentials__export-note">
          The file downloads through a short-lived link scoped to this export
          and to you. Generating it is recorded in the audit log.
        </p>
      </article>

      <p class="credentials__pending" role="note">
        Credential revocation is not available from this surface yet.
      </p>
    </template>
  </WorkflowPageShell>
</template>

<style scoped>
.credentials__restricted,
.credentials__hint,
.credentials__error,
.credentials__notice,
.credentials__pending {
  margin: 0;
  padding: var(--m-space-3);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
}

.credentials__error {
  border-color: color-mix(
    in srgb,
    var(--m-status-danger, #cc792f) 40%,
    var(--m-border-default)
  );
  color: var(--m-status-danger, #cc792f);
}

.credentials__pending {
  border-style: dashed;
  color: var(--m-text-muted);
}

.credentials__export {
  display: grid;
  gap: var(--m-space-3);
  padding: var(--m-space-4);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
  background: var(--m-surface-raised);
}

.credentials__export-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: var(--m-space-3);
}

.credentials__export-title {
  margin: 0;
  font-family: var(--m-font-heading);
  font-size: var(--m-text-lg);
}

.credentials__download {
  display: inline-flex;
  align-items: center;
  min-height: 2.75rem;
  padding: 0 var(--m-space-4);
  border: 1px solid transparent;
  border-radius: var(--m-radius-sm);
  background: var(--m-action-primary-bg);
  color: var(--m-action-primary-text);
  font: inherit;
  font-weight: 600;
  cursor: pointer;
}

.credentials__download:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.credentials__export-contains,
.credentials__export-note {
  margin: 0;
}

.credentials__export-note {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
}

.credentials__facts {
  display: grid;
  gap: var(--m-space-2);
  margin: 0;
}

.credentials__fact {
  display: grid;
  grid-template-columns: minmax(5rem, 8rem) 1fr;
  gap: var(--m-space-3);
}

.credentials__fact dt {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
  font-weight: 600;
}

.credentials__fact dd {
  margin: 0;
}

.credentials__columns {
  overflow-wrap: anywhere;
  font-family: var(--m-font-mono, monospace);
  font-size: var(--m-text-sm);
}

@media (max-width: 40rem) {
  .credentials__fact {
    grid-template-columns: 1fr;
    gap: var(--m-space-1);
  }
}
</style>
