replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: !env PS_DATA_SOURCE_SSLMODE

storage:
  type: postgresql
  uri: !env PS_BUCKET_STORAGE_URI
  sslmode: !env PS_BUCKET_STORAGE_SSLMODE

port: 80

sync_config:
  path: /config/sync-config.yaml

client_auth:
  jwks_uri: !env PS_JWKS_URI
  audience:
    - !env PS_JWT_AUDIENCE

telemetry:
  disable_telemetry_sharing: true

system:
  logging:
    level: !env PS_LOG_LEVEL
    format: json
