<script setup lang="ts">
import { computed, ref } from "vue";

import { meridianErrorMessage } from "@/api/meridianApi";
import { useLocalNodeReachable } from "@/offline/useConnectivity";
import {
  downloadReportingExport,
  type ReportingExportAuthority,
  type ReportingExportDescriptor,
} from "@/reporting/reportingExports";

/**
 * The exports a caller may run, each stated before it is generated (M18.26;
 * REPORT-014, REPORT-015; CLIENT-019, CLIENT-020).
 *
 * One component behind both export surfaces, because the difference between
 * them is the scope they run at and not what they owe a reader. What they owe
 * is REPORT-014's list: what the rows are, which columns come back, and which
 * fields are deliberately absent — so an organizer sees that emergency contacts
 * are excluded without having to open the file (REPORT-010).
 *
 * `scopeStatement` is the caller's, because only the surface knows which scope
 * it is offering. `departmentId` is the narrowing that goes with every request:
 * the department surface always sends its own department, the organizer surface
 * sends one only when somebody picked it, and neither can widen anything — the
 * node refuses a department outside the caller's scope rather than serving it.
 *
 * Nothing here decides authorization. `authority` already holds only the
 * exports this caller may run, and an export they may not is absent rather than
 * disabled (CLIENT-005); the node refuses the request either way (CLIENT-006).
 */
const props = withDefaults(
  defineProps<{
    authority: ReportingExportAuthority;
    /** What this surface's scope is, in the words the surface would use. */
    scopeStatement: string;
    /** The `department_id` narrowing to send, or null for the caller's own scope. */
    departmentId?: string | null;
  }>(),
  { departmentId: null },
);

const nodeReachable = useLocalNodeReachable();

/**
 * Exports are generated by the node, so there is nothing to run without one.
 *
 * Refused where it stands rather than queued: an export is not a command and
 * the outbox has nothing to replay (data/API 7.2, technical spec 19.2).
 */
const isOfflineBlocked = computed(() => !nodeReachable.value);

const error = ref<string | null>(null);
const notice = ref<string | null>(null);
const busyExportId = ref<string | null>(null);

/**
 * Run one export (CLIENT-019, CLIENT-020).
 *
 * The endpoint comes off the descriptor that was rendered, so the button runs
 * the export it is labelled with rather than whichever one a list index landed
 * on.
 */
async function runExport(descriptor: ReportingExportDescriptor): Promise<void> {
  if (isOfflineBlocked.value || busyExportId.value !== null) {
    return;
  }

  error.value = null;
  notice.value = null;
  busyExportId.value = descriptor.id;

  try {
    const issued = await downloadReportingExport(
      descriptor,
      props.authority.eventId,
      props.departmentId,
    );

    notice.value =
      issued.expiresAt === null
        ? `${descriptor.label} is downloading.`
        : `${descriptor.label} is downloading. The link expires at ${formatExpiry(issued.expiresAt)}.`;
  } catch (caught) {
    error.value = meridianErrorMessage(
      caught,
      `Unable to export ${descriptor.label.toLowerCase()}. Check the connection to this node and try again.`,
    );
  } finally {
    busyExportId.value = null;
  }
}

/** The moment a link stops working, in the reader's own time zone. */
function formatExpiry(expiresAt: string): string {
  const moment = new Date(expiresAt);

  return Number.isNaN(moment.getTime())
    ? expiresAt
    : moment.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
}
</script>

<template>
  <div class="reporting-exports">
    <p v-if="isOfflineBlocked" class="reporting-exports__hint" role="status">
      Exports are generated by the node and require a server connection. They are
      not queued for later.
    </p>

    <p v-if="error" class="reporting-exports__error" role="alert">{{ error }}</p>

    <p v-if="notice" class="reporting-exports__notice" role="status">
      {{ notice }}
    </p>

    <article
      v-for="descriptor in authority.exports"
      :key="descriptor.id"
      class="reporting-exports__export"
    >
      <header class="reporting-exports__export-header">
        <h2 class="reporting-exports__export-title">{{ descriptor.label }}</h2>
        <button
          type="button"
          class="reporting-exports__download"
          :aria-label="`Export ${descriptor.label}`"
          :disabled="isOfflineBlocked || busyExportId === descriptor.id"
          @click="runExport(descriptor)"
        >
          {{
            busyExportId === descriptor.id
              ? "Preparing…"
              : `Export ${descriptor.format}`
          }}
        </button>
      </header>

      <p class="reporting-exports__export-contains">{{ descriptor.contains }}</p>

      <!--
        Scope and exclusions before generation (REPORT-010, REPORT-014). The
        scope is the rule the node applies, not a prediction of its outcome.
      -->
      <dl class="reporting-exports__facts">
        <div class="reporting-exports__fact">
          <dt>Scope</dt>
          <dd>{{ scopeStatement }}</dd>
        </div>
        <div class="reporting-exports__fact">
          <dt>Excluded</dt>
          <dd>{{ descriptor.excludes.join(", ") }}.</dd>
        </div>
        <div class="reporting-exports__fact">
          <dt>Columns</dt>
          <dd class="reporting-exports__columns">
            {{ descriptor.columns.join(", ") }}
          </dd>
        </div>
        <!--
          A column that rides along only when a rule holds is stated as the rule
          rather than as a column, because which of the two this caller gets is
          the node's answer and not this surface's (REPORT-009, REPORT-010).
        -->
        <div
          v-if="descriptor.conditionalColumns"
          class="reporting-exports__fact"
        >
          <dt>Sometimes included</dt>
          <dd>
            <span class="reporting-exports__columns">
              {{ descriptor.conditionalColumns.columns.join(", ") }}
            </span>
            — {{ descriptor.conditionalColumns.condition }}
          </dd>
        </div>
      </dl>

      <p class="reporting-exports__export-note">
        The file downloads through a short-lived link scoped to this export and
        to you. Generating it is recorded in the audit log.
      </p>
    </article>
  </div>
</template>

<style scoped>
.reporting-exports {
  display: grid;
  gap: var(--m-space-3);
}

.reporting-exports__hint,
.reporting-exports__error,
.reporting-exports__notice {
  margin: 0;
  padding: var(--m-space-3);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
}

.reporting-exports__error {
  border-color: color-mix(
    in srgb,
    var(--m-status-danger, #cc792f) 40%,
    var(--m-border-default)
  );
  color: var(--m-status-danger, #cc792f);
}

.reporting-exports__export {
  display: grid;
  gap: var(--m-space-3);
  padding: var(--m-space-4);
  border: 1px solid var(--m-border-default);
  border-radius: var(--m-radius-sm);
  background: var(--m-surface-raised);
}

.reporting-exports__export-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: var(--m-space-3);
}

.reporting-exports__export-title {
  margin: 0;
  font-family: var(--m-font-heading);
  font-size: var(--m-text-lg);
}

.reporting-exports__download {
  display: inline-flex;
  align-items: center;
  min-height: 2.75rem;
  padding: 0 var(--m-space-4);
  border: 1px solid transparent;
  border-radius: var(--m-radius-sm);
  background: var(--m-action-primary-bg);
  color: var(--m-action-primary-text);
  font: inherit;
  font-weight: 600;
  cursor: pointer;
}

.reporting-exports__download:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.reporting-exports__export-contains,
.reporting-exports__export-note {
  margin: 0;
}

.reporting-exports__export-note {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
}

.reporting-exports__facts {
  display: grid;
  gap: var(--m-space-2);
  margin: 0;
}

.reporting-exports__fact {
  display: grid;
  grid-template-columns: minmax(5rem, 9rem) 1fr;
  gap: var(--m-space-3);
}

.reporting-exports__fact dt {
  color: var(--m-text-muted);
  font-size: var(--m-text-sm);
  font-weight: 600;
}

.reporting-exports__fact dd {
  margin: 0;
}

.reporting-exports__columns {
  overflow-wrap: anywhere;
  font-family: var(--m-font-mono, monospace);
  font-size: var(--m-text-sm);
}

@media (max-width: 40rem) {
  .reporting-exports__fact {
    grid-template-columns: 1fr;
    gap: var(--m-space-1);
  }
}
</style>
